# SWMAL Exercise

#### Qa Given the following $\mathbf{x}^{(i)}$'s, construct and print the $\mathbf X$ matrix in python.

$$
    \ar{rl}{
      \bx\pown{1} &= \ac{c}{ 1\\ 2\\ 3} \\
      \bx\pown{2} &= \ac{c}{ 4\\ 2\\ 1} \\
      \bx\pown{3} &= \ac{c}{ 3\\ 8\\ 5} \\
      \bx\pown{4} &= \ac{c}{-9\\-1\\ 0}
    }
$$

To define the above matrix in python, we utilize the `np.array` function in `numpy` to define the values as a list of lists for each row in the matrix.

In [17]:
import numpy as np

y_true = np.array([1,2,3,4]) # NOTE:  you'll need this later

X = np.array([
    [1, 2, 3],
    [4, 2, 1],
    [3, 8, 5],
    [-9, -1, 0]
])

print(X)

[[ 1  2  3]
 [ 4  2  1]
 [ 3  8  5]
 [-9 -1  0]]


#### Qb Implement the $\norm{1}$ and $\norm{2}$ norms for vectors in python.

Implementatin of L1- and L2 norms in pure python.


In [16]:
import math
def L1(vector):
    if vector.ndim != 1:
        raise ValueError("Input should be a 1D vector")
    sum = 0.0
    for i in range(len(vector)):
        sum += (vector[i]**2)**0.5

    return sum

def L2(vector):
    if vector.ndim != 1:
        raise ValueError("Input should be a 1D vector")
    
    sum = 0.0
    for i in range(len(vector)):
        sum += vector[i]**2
    return sum ** 0.5

def L2Dot(vector):
    return np.dot(vector.T,vector)**0.5

# TEST vectors: here I test your implementation...calling your L1() and L2() functions
tx=np.array([1, 2, 3, -1])
ty=np.array([3,-1, 4,  1])

expected_d1=8.0
expected_d2=4.242640687119285

d1=L1(tx-ty)
d2=L2(tx-ty)

print(f"tx-ty={tx-ty}, d1-expected_d1={d1-expected_d1}, d2-expected_d2={d2-expected_d2}")

eps=1E-9 
assert math.fabs(d1-expected_d1)<eps, "L1 dist seems to be wrong" 
assert math.fabs(d2-expected_d2)<eps, "L2 dist seems to be wrong" 

print("OK(part-1)")

d2dot=L2Dot(tx-ty)
print("d2dot-expected_d2=",d2dot-expected_d2)
assert math.fabs(d2dot-expected_d2)<eps, "L2Ddot dist seem to be wrong" 
print("OK(part-2)")

tx-ty=[-2  3 -1 -2], d1-expected_d1=0.0, d2-expected_d2=0.0
OK(part-1)
d2dot-expected_d2= 0.0
OK(part-2)


The functions return a difference of `0.0`, which means that the implementation is correct according to the test.

### Qc Construct the Root Mean Square Error (RMSE) function (Equation 2-1 [HOML]).

RMSE is used to se the difference between the predicted values and therefore the performance of the model that we are testing. The RMSE function always returns a non-negative number. The lower the number, the better the model fits the data. If its 0 the models predictions are exact.

The number can be as high as our `y_true` values.

In the code below the prediceted values are made with the `h(X)`function.

In [ ]:
from math import fabs

# Dummy h function:
def h(X):    
    if X.ndim!=2:
        raise ValueError("excpeted X to be of ndim=2, got ndim=",X.ndim)
    if X.shape[0]==0 or X.shape[1]==0:
        raise ValueError("X got zero data along the 0/1 axis, cannot continue")
    return X[:,0]

def RMSE(X, y):
    if X.shape != y.shape:
        raise ValueError(f"X shape ({X.shape}) should be the same as y ({y.shape})")

    return L2(X-y) / np.sqrt(len(y))


# Calls your RMSE() function:
r=RMSE(h(X), y_true)

# TEST vector:
eps=1E-9
expected=6.57647321898295
print(f"RMSE={r}, diff={r-expected}")
assert fabs(r-expected)<eps, "your RMSE dist seems to be wrong" 

print("OK")

RMSE=6.576473218982953, diff=2.6645352591003757e-15
OK


#### Qd Similar construct the Mean Absolute Error (MAE) function (Equation 2-2 [HOML]) and evaluate it.

Implementation of the MAE equation:

$\text{MAE}(\mathbf{X}, h) = \frac{1}{m} \sum_{i=1}^{m} \left| h\!\left(\mathbf{x}^{(i)}\right) - y^{(i)} \right|$

In [15]:
def MAE(X, y):
    if X.shape != y.shape:
        raise ValueError(f"X shape ({X.shape}) should be the same as y ({y.shape})")
    return L1(X - y) / len(y)

# Calls your MAE function:
r=MAE(h(X), y_true)

# TEST vector:
expected=3.75
print(f"MAE={r}, diff={r-expected}")
assert fabs(r-expected)<eps, "MAE dist seems to be wrong" 

print("OK")

MAE=3.75, diff=0.0
OK


The MAE is 3.75 which gives us a difference of 0.0.

#### Qe Robust Code 

In our functions, we have made them more robust by adding error handling, such as using `ndim`, `ValueError` and `shape` to check if the parameters passed to the function is a vector or if it has the shape that we expect.

By doint the exercises on cost function a deeper understanding of the concepts are achieved.
It has also proven a good foundating in the python way of doing Machine Learning. By using the `fail fast` method, its possible to save much time not spending time on uneccesary computations that eventually would end in an error cased by wrong data or shape.

Its also very keen to be reusing robust code in Machine Learning. By having a collection of small, effective and safe code that can be referenced in the furture, is something to be appreciated.